### ISSUE TITLE
Get deployment of mapserver working on pg01 

### ISSUE THREAD

**Issue by Mappboy** [geogeeks-au/maps-for-lost-towns#19]
Currently experiencing a problem with mapscript and mapscript.io

**Comment by Mappboy** [comment]
https://github.com/sourcepole/ruby_mapscript/issues/3

**Comment by johnwbryant** [comment]
may be worth touching base next hack night or before with @attentive as he has run through some of this on his machine

**Comment by Mappboy** [comment]
@johnwbryant Is he running ubuntu ? Seems to be ubuntu/debian related

**Comment by Mappboy** [comment]
Doesn't matter got it working. Login in as test_user@geogeeks.org password is password.

**Comment by attentive** [comment]
Good stuff. Yeah, I'm running mapwarper on the Trusty image the project has the vagrant configuration for. I found the apt and gem configuration scripts didn't quite work out of the box.
