### ISSUE TITLE
Are higher resolutions available?

### ISSUE THREAD

**Issue by samwilson** [geogeeks-au/maps-for-lost-towns#6]
It occurred to me that these JPGs are probably derived from higher-quality images. Is that the case? Can we get access to higher resolutions? A few of the maps I've been looking at are not very readable, and some quite indecipherable.

Here's 150ppi vs 300ppi (at abut the same size):
![Arthur Head](https://cloud.githubusercontent.com/assets/213655/13865907/6ac0fe84-eceb-11e5-98cb-b237a2e2b283.png) ![other crop](https://cloud.githubusercontent.com/assets/213655/13866186/e007011e-eced-11e5-8f64-119111f958af.png)

(other map is [this](https://commons.wikimedia.org/wiki/File:Eaa2623_001_0002138_00031_k.jpg))

**Comment by keithamoss** [comment]
Not sure - will ask!

**Comment by keithamoss** [comment]
@samwilson Which items in the SRO catalogue were the two examples above from?

**Comment by samwilson** [comment]
The first is [this](https://archive.sro.wa.gov.au/index.php/part-of-plan-for-mole-harbour-by-j-s-roe-s-g-also-copy-filed-with-pwd-892-00884) (the Freo mole one I've been using as a Commons test), and the second is not part of this collection but just an example of a similar type of document to illustrate that perhaps we're not looking for super-high resolution (as sometimes is wanted for e.g. photographic restoration etc.).

I've not found any in the SRO collection at higher than 150ppi yet. I guess there aren't any. Maybe that's okay for the majority of these anyway; it's just that there are some labels that are illegible at that resolution.

**Comment by keithamoss** [comment]
Yeah, most are 150ppi. A few 300ppi.
