### ISSUE TITLE
Scraping SRO's digital objects collection

### ISSUE THREAD

**Issue by keithamoss** [geogeeks-au/maps-for-lost-towns#8]
Is there an API? If not, can we get a data dump? If not, we'll scrape.

Will ask SRO.

Next: #11

**Comment by keithamoss** [comment]
## If we are in want of an API...

Let's scrape the digital objects collection from SRO.

## Process
- Scrape /digitalobject/browse
- Find all image preview tiles with links to /{item-name}
- Scrape /{item-name}
- For each item listed in the page, request its page
- Extract the fields in a meaningful and machine-readable fashion
- time.sleep(1) to be nice to SRO's servers
- Save to disk as a nice JSON blob
- time.sleep(1) to be nice to SRO's servers
- Iterate to next page
- > Rinse and repeat until we've got all 6,600 objects.

## Potential Challenges
- Can we reliably link items to the filenames we have on the harddrive?
- How many of the items in SRO's digital objects collection are not maps?
- Do we need the Dublin Core XML, or is scraping the HTML enough?

## Test Data

**Page**
https://archive.sro.wa.gov.au/index.php/a-c-gregory-bejoording-to-sturt-river-through-wongan-hills-021

**Dublin Core XML**
https://archive.sro.wa.gov.au/index.php/a-c-gregory-bejoording-to-sturt-river-through-wongan-hills-021;dc?sf_format=xml

**Dublin Core Metadata Schema**
http://www.openarchives.org/OAI/2.0/oai_dc.xsd

**Page**
https://archive.sro.wa.gov.au/index.php/plan-showing-locations-for-the-salvation-army-north-north-east-of-collie-by-n-j-moore-fieldbooks-20-24-scale-20-chains-to-an-inch-wellington-160

**Image**
https://archive.sro.wa.gov.au/uploads/r/srowa/3/2/32111b70dfa1d0759802feedc15efefc391474bb4509a1d02999ea229e8346be/Cons_3869_Wellington_160.jpg

**Dublin Core XML**
https://archive.sro.wa.gov.au/index.php/plan-showing-locations-for-the-salvation-army-north-north-east-of-collie-by-n-j-moore-fieldbooks-20-24-scale-20-chains-to-an-inch-wellington-160;dc?sf_format=xml

**Comment by samwilson** [comment]
I guess it's unlikely that they'll upgrade to the latest AtoM, that has an API?

**Comment by keithamoss** [comment]
In the short term, certainly unlikely, @samwilson.

They've suggested they could send us a database dump in the next couple of weeks though - so we may not have to scrape at all!

**Comment by samwilson** [comment]
Oh that's cool! :)

**Comment by keithamoss** [comment]
Checkout https://github.com/geogeeks-au/maps-for-lost-towns/blob/master/scrapers/SRO%20Digital%20Objects%20Scraper.ipynb for a partially completed scraper.

**Comment by keithamoss** [comment]
The scraper has finished running against SRO! We've now got all 6,745 maps in the database in the new `sro_digital_objects_collection` table.

Code is here: https://github.com/geogeeks-au/maps-for-lost-towns/blob/master/scrapers/SRO%20Digital%20Objects%20Scraper.ipynb
CSV dump is here: https://github.com/geogeeks-au/maps-for-lost-towns/blob/master/scrapers/sro_digital_objects_collection.csv

<img width="1280" alt="screen shot 2016-04-29 at 16 06 43" src="https://cloud.githubusercontent.com/assets/1672960/14910967/8238bfa2-0e24-11e6-8384-65eb7ca2dd40.png">
